services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: kartverket_tables
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  gruppe6_kartverket.mvc:
    build:
      context: .
      dockerfile: Gruppe6_Kartverket.Mvc/Dockerfile
    image: gruppe6_kartverket.mvc:latest
    ports:
      - "5001:80"
    depends_on:
      mariadb:
        condition: service_started   # Wait for mariadb to start
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mariadb;Port=3306;Database=kartverket_tables;User=root;Password=123"
      PATH: "$PATH:/root/.dotnet/tools"
    networks:
      mynetwork:
        aliases:
          - gruppe6_kartverket.mvc
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro
      - ./Gruppe6_Kartverket.Mvc/keys:/app/keys
    command: [ "dotnet", "ef", "database", "update", "--project", "/src/Gruppe6_Kartverket.Mvc/Gruppe6_Kartverket.Mvc.csproj" ]
    
networks:
  mynetwork:
    driver: bridge

volumes:
  db_data: