services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: passord123
      MYSQL_DATABASE: kartverket_tables
      MYSQL_USER: root
      MYSQL_PASSWORD: passord123
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  gruppe6_kartverket.mvc:
    build:
      context: .
      dockerfile: Gruppe6_Kartverket.Mvc/Dockerfile
    image: gruppe6_kartverket.mvc:latest
    ports:
      - "5001:80"
    depends_on:
      mariadb:
        condition: service_started   # Wait for mariadb to start
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mariadb;Port=3306;Database=kartverket_tables;User=root;Password=passord123"
    networks:
      mynetwork:
    volumes:
      - ./Gruppe6_Kartverket.Mvc/keys:/app/keys
    command: [ "dotnet", "ef", "database", "update", "--project", "/src/Gruppe6_Kartverket.Mvc/Gruppe6_Kartverket.Mvc.csproj" ]

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data: