services:
  gruppe6_kartverket.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
     # ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro  #Windows
     #- ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro                  #Windows
     - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro   #Mac and Linux
     - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro                     #Mac and Linux