services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: kartverket_tables
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"  # Exposing port 3306 inside the container as port 3307 on the host
    volumes:
      - db_data:/var/lib/mysql  # Ensuring data persists between container restarts
    networks:
      - backend

  gruppe6_kartverket.mvc:
    build:
      context: .
      dockerfile: gruppe6_Kartverket.mvc/Dockerfile
    image: gruppe6_kartverket.mvc:latest
    ports:
      - "5001:80"  # Exposing the MVC app on port 5001 of the host
    depends_on:
      - mariadb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mariadb;Port=3306;Database=kartverket_tables;User=root;Password=123"
    # command: bash -c "for i in \$(seq 1 30); do dotnet ef database update && break || (echo 'Waiting for DB...'; sleep 5); done; dotnet WebApplication1.dll"  # Apply migrations and run the app
    networks:
      - backend
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro
      - ./Gruppe6_Kartverket.Mvc/keys:/app/keys # Map Keys folder

networks:
  backend:
    driver: bridge  # Ensures containers are connected to the same network

volumes:
  db_data:  # Ensures that the database data persists even if the container is removed
