services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: kartverket_tables
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
  
  gruppe6_kartverket.mvc:
    build:
      context: .
      dockerfile: gruppe6_Kartverket.mvc/Dockerfile
    image: gruppe6_kartverket.mvc:latest
    ports:
      - "5001:8080"
    depends_on:
      - mariadb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=kartverket_tables;User=root;Password=123"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge