services:
  gruppe6_kartverket.mvc:
    image: ${DOCKER_REGISTRY-}gruppe6_kartverket.mvc_1
    build:
      context: .
      dockerfile: gruppe6_Kartverket.mvc/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mariadb
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=kartverket_tables;User=root;Password=Mnarild12!"
    networks:
      - backend

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Mnarild12!
      MYSQL_DATABASE: kartverket_tables
      MYSQL_USER: root
      MYSQL_PASSWORD: Mnarild12!
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: