# services:
#   gruppe6_kartverket.mvc:
#     image: ${DOCKER_REGISTRY-}gruppe6kartverketmvc
#     build:
#       context: .
#       dockerfile: Gruppe6_Kartverket.Mvc/Dockerfile
version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Mnarild12!
      MYSQL_DATABASE: kartverket_tables
      MYSQL_USER: root
      MYSQL_PASSWORD: Mnarild12!
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  gruppe6_kartverket.mvc:
    image: ${DOCKER_REGISTRY-}gruppe6kartverketjorgenbranch2
    build:
      context: .
      dockerfile: Gruppe6_Kartverket.Mvc/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mariadb
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=kartverket_tables;User=root;Password=Mnarild12!;"
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend: