// <auto-generated />
using System;
using Gruppe6_Kartverket.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gruppe6_Kartverket.Mvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gruppe6_Kartverket.Mvc.Models.Database.CaseLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("GeoJSON")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("LocationId");

                    b.ToTable("CaseLocations");
                });

            modelBuilder.Entity("Gruppe6_Kartverket.Mvc.Models.Database.CaseRecord", b =>
                {
                    b.Property<int>("CaseRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CaseRecordId"));

                    b.Property<DateTime>("CaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CaseDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CaseRecordId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("CaseRecords");
                });

            modelBuilder.Entity("Gruppe6_Kartverket.Mvc.Models.Database.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("UserId");

                    b.HasIndex("UserType");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gruppe6_Kartverket.Mvc.Models.Database.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("Gruppe6_Kartverket.Mvc.Models.Database.UserTypes", b =>
                {
                    b.Property<string>("UserType")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UserTypeDescription")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserType");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("Gruppe6_Kartverket.Mvc.Models.Database.CaseRecord", b =>
                {
                    b.HasOne("Gruppe6_Kartverket.Mvc.Models.Database.CaseLocation", "CaseLocation")
                        .WithMany("CaseRecords")
                        .HasForeignKey("LocationId");

                    b.HasOne("Gruppe6_Kartverket.Mvc.Models.Database.User", "User")
                        .WithMany("CaseRecords")
                        .HasForeignKey("UserId");

                    b.Navigation("CaseLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gruppe6_Kartverket.Mvc.Models.Database.User", b =>
                {
                    b.HasOne("Gruppe6_Kartverket.Mvc.Models.Database.UserTypes", "UserTypeNavigation")
                        .WithMany("Users")
                        .HasForeignKey("UserType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTypeNavigation");
                });

            modelBuilder.Entity("Gruppe6_Kartverket.Mvc.Models.Database.UserInfo", b =>
                {
                    b.HasOne("Gruppe6_Kartverket.Mvc.Models.Database.User", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("Gruppe6_Kartverket.Mvc.Models.Database.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gruppe6_Kartverket.Mvc.Models.Database.CaseLocation", b =>
                {
                    b.Navigation("CaseRecords");
                });

            modelBuilder.Entity("Gruppe6_Kartverket.Mvc.Models.Database.User", b =>
                {
                    b.Navigation("CaseRecords");

                    b.Navigation("UserInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Gruppe6_Kartverket.Mvc.Models.Database.UserTypes", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
